/* pvm.h - Poke Virtual Machine.  */

/* Copyright (C) 2018 Jose E. Marchesi */

/* This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <config.h>

#include <gc.h>

#include "pvm.h"

static struct pvm_state pvm_state;

void
pvm_init (void)
{
  pvm_initialize ();
  /* XXX: but then add it by hand.  */
  /* jitterlispvm_disable_final_exitvm (); */
  GC_INIT ();
  pvm_state_initialize (&pvm_state);
}

void
pvm_shutdown (void)
{
  pvm_state_finalize (&pvm_state);
  GC_gcollect();
  pvm_finalize ();
}

enum pvm_exit_code
pvm_run (pvm_program prog, pvm_val *res)
{
  pvm_state.pvm_state_backing.result_value = PVM_NULL;
  pvm_state.pvm_state_backing.exit_code = PVM_EXIT_OK;

  /* XXX: get the run-time environment as an argument and set it in
     pvm_state_runtime before interpreting the program. */

  /* Jitter supports maintaining a VM state which is splitted in
     `backing' and `runtime', so the question arises what to put in
     what part of the state.

     According to the comments generated by jitterc:

     "The machine state is separated into the backing and the more
     compact runtime data structures, to be allocated in registers as
     far as possible.  These are just a forward-declarations: the
     actual definitions are machine-generated."
 
     "The state backing and runtime are initialized at the same time,
     and in fact the distinction between them is invisible to the VM
     user."

     So it looks like both `backing' and `runtime' are available at
     runtime, but accessing runtime is much more efficient because it
     is kept in host machine registers if possible.

     It is a good idea to put the link to the current environment in
     the runtime state, because it is used often.  */
  
  pvm_interpret (prog, &pvm_state);

  if (res != NULL)
    *res = pvm_state.pvm_state_backing.result_value;

  return pvm_state.pvm_state_backing.exit_code;
}

const char *
pvm_error (enum pvm_exit_code code)
{
  static char *pvm_error_strings[]
    = { "ok", "error", "division by zero" };

  return pvm_error_strings[code];
}

