/* pvm.h - Poke Virtual Machine.  */

/* Copyright (C) 2018 Jose E. Marchesi */

/* This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <config.h>

#include <gc.h>
#include <xalloc.h>
#include <string.h>

#include "pvm.h"

/* The following struct defines a Poke Virtual Machine.  */

#define PVM_STATE_RESULT_VALUE(PVM)                     \
  ((PVM)->pvm_state.pvm_state_backing.result_value)
#define PVM_STATE_EXIT_CODE(PVM)                        \
  ((PVM)->pvm_state.pvm_state_backing.exit_code)

struct pvm
{
  /* Note that the contents of the struct pvm_state are defined in the
     state-struct-backing-c and state-struct-runtime-c entries in
     pvm.jitter.  */
  struct pvm_state pvm_state;
};

pvm
pvm_init (void)
{
  pvm pvm = xmalloc (sizeof (struct pvm));
  memset (pvm, 0, sizeof (struct pvm));
  
  /* Initialize the VM subsystem.  */
  pvm_initialize ();

  /* Start the Boehm garbage collector, which is used to manage PVM
     values and environments.  */
  GC_INIT ();

  /* Initialize the VM state.  */
  /* XXX: create an initial run-time environment.  */
  pvm_state_initialize (&pvm->pvm_state);

  return pvm;
}

void
pvm_shutdown (pvm pvm)
{
  /* Finalize the VM state.  */
  pvm_state_finalize (&pvm->pvm_state);

  /* Make the garbage collector to collect the memory used by the
     PVM.  */
  GC_gcollect();

  /* Finalize the VM subsystem.  */
  pvm_finalize ();

  free (pvm);
}

enum pvm_exit_code
pvm_run (pvm pvm, pvm_program prog, pvm_val *res)
{
  PVM_STATE_RESULT_VALUE (pvm) = PVM_NULL;
  PVM_STATE_EXIT_CODE (pvm) = PVM_EXIT_OK;

  /* XXX: get the run-time environment as an argument and set it in
     pvm_state_runtime before interpreting the program. */

  /* Jitter supports maintaining a VM state which is splitted in
     `backing' and `runtime', so the question arises what to put in
     what part of the state.

     According to the comments generated by jitterc:

     "The machine state is separated into the backing and the more
     compact runtime data structures, to be allocated in registers as
     far as possible.  These are just a forward-declarations: the
     actual definitions are machine-generated."
 
     "The state backing and runtime are initialized at the same time,
     and in fact the distinction between them is invisible to the VM
     user."

     So it looks like both `backing' and `runtime' are available at
     runtime, but accessing runtime is much more efficient because it
     is kept in host machine registers if possible.

     It is a good idea to put the link to the current environment in
     the runtime state, because it is used often.  */
  
  pvm_interpret (prog, &pvm->pvm_state);

  if (res != NULL)
    *res = PVM_STATE_RESULT_VALUE (pvm);

  return PVM_STATE_EXIT_CODE (pvm);
}

const char *
pvm_error (enum pvm_exit_code code)
{
  static char *pvm_error_strings[]
    = { "ok", "error", "division by zero" };

  return pvm_error_strings[code];
}

